---
extends: default

ignore:
  - .roles/
  - .ansible/
  - .github/
  - .pre-commit-config.yaml

rules:
  line-length:
    max: 200
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  comments:
    min-spaces-from-content: 1
  document-start:
    present: true
