---
service_name: uptime-kuma
service_port: "443"
service_data_dir: /var/lib/uptime-kuma
service_config_dir: /etc/uptime-kuma
service_user: uptime-kuma
service_domain: uptime-kuma.local.iamrobertyoung.co.uk
service_container_name: uptime-kuma

backup_image_name: backup-toolkit
backup_image_tag: local
backup_from: /data
backup_mosquitto_host: mosquitto.local.iamrobertyoung.co.uk
backup_mosquitto_username: "home-assistant"
backup_mosquitto_password: "password"
backup_bucket_name: "home-server-backup.iamrobertyoung.co.uk"

traefik_config_dir: /etc/traefik

quadlet_dir: /etc/containers/systemd

backup_cron: "*-*-* 04:00:00"

cert_dir: /etc/uptime-kuma/certs
