---
- name: Uptime Kuma server configuration
  hosts: uptime_kuma
  vars:
    hostname: uptime-kuma
    domain: local.iamrobertyoung.co.uk
    fqdn: "{{ hostname }}.{{ domain }}"

  roles:
    - role: configure-system
      tags: [configure-system]

    - role: shell
      tags: [shell]
      vars:
        shell_hostname: "{{ hostname }}"
        shell_user: noxious
        shell_home_directory: /home/noxious

    - role: shell
      tags: [shell]
      vars:
        shell_hostname: "{{ hostname }}"
        shell_user: root
        shell_home_directory: /root
        shell_show_pretty_info: false

    - role: podman
      tags: [podman]

    - role: telegraf
      tags: [telegraf]
      vars:
        telegraf_influxdb_url: "https://influxdb.{{ domain }}"
        telegraf_influxdb_port: 8086
        telegraf_influxdb_organisation: "0dd8df669872ba9e"
        telegraf_influxdb_token: "{{ lookup('aws_ssm', '/homelab/influxdb/token', region='eu-west-1') }}"
        telegraf_influxdb_bucket: "home-server"

    - role: step-ca-client
      tags: [step-ca-client]
      vars:
        step_ca_client_provisioner_password: "{{ lookup('aws_ssm', '/homelab/step-ca/ansible-password', region='eu-west-1') }}"
        step_ca_client_post_renew_commands:
          - "mkdir -p /etc/uptime-kuma/certs"
          - "cp /etc/ssl/certs/{{ fqdn }}.crt /etc/uptime-kuma/certs/"
          - "cp /etc/ssl/private/{{ fqdn }}.pem /etc/uptime-kuma/certs/"
          - "podman kill --signal=HUP traefik || echo 'Traefik not running, skipping HUP signal'"

    - role: syslog
      tags: [syslog]
      vars:
        syslog_fqdn: "{{ fqdn }}"

    - role: wazuh-agent
      tags: [wazuh-agent]

    - role: uptime-kuma
      tags: [uptime-kuma]
      vars:
        backup_aws_access_key: "{{ lookup('aws_ssm', '/homelab/aws/access-key', region='eu-west-1') }}"
        backup_aws_secret_access_key: "{{ lookup('aws_ssm', '/homelab/aws/secret-access-key', region='eu-west-1') }}"
        backup_aws_region: eu-west-2
        backup_mosquitto_password: "{{ lookup('aws_ssm', '/homelab/mosquitto/home-assistant-password', region='eu-west-1') }}"
